ALTER TABLE '_countries'
    CHANGE 'country_id' 'id' INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ADD COLUMN 'title' VARCHAR(150) INDEX NOT NULL AFTER 'id',
    DROP 'title_ru',
    DROP 'title_ua',
    DROP 'title_be',
    DROP 'title_en',
    DROP 'title_es',
    DROP 'title_pt',
    DROP 'title_de',
    DROP 'title_fr',
    DROP 'title_it',
    DROP 'title_pl',
    DROP 'title_ja',
    DROP 'title_lt',
    DROP 'title_lv',
    DROP 'title_cz';

ALTER TABLE '_regions'
    CHANGE 'region_id' 'id' INT(11) NOT NULL AUTO_INCREMENT,
    ADD COLUMN 'title' VARCHAR(150) INDEX NOT NULL AFTER 'id',
    ADD CONSTRAINT 'country_id' FOREIGN KEY('country_id') REFERENCES '_countries'('id'),
    DROP 'title_ru',
    DROP 'title_ua',
    DROP 'title_be',
    DROP 'title_en',
    DROP 'title_es',
    DROP 'title_pt',
    DROP 'title_de',
    DROP 'title_fr',
    DROP 'title_it',
    DROP 'title_pl',
    DROP 'title_ja',
    DROP 'title_lt',
    DROP 'title_lv',
    DROP 'title_cz';

ALTER TABLE '_cities'
    CHANGE 'city_id' 'id' INT(11) NOT NULL AUTO_INCREMENT,
    ADD COLUMN 'title' VARCHAR (150) INDEX NOT NULL AFTER 'id',
    ADD CONSTRAINT 'country_id' FOREIGN KEY('country_id') REFERENCES '_countries'('id'),
    ADD CONSTRAINT 'region_id' FOREIGN KEY('region_id') REFERENCES '_regions'('id'),
    DROP 'title_ru',
    DROP 'title_ua',
    DROP 'title_be',
    DROP 'title_en',
    DROP 'title_es',
    DROP 'title_pt',
    DROP 'title_de',
    DROP 'title_fr',
    DROP 'title_it',
    DROP 'title_pl',
    DROP 'title_ja',
    DROP 'title_lt',
    DROP 'title_lv',
    DROP 'title_cz',
    DROP 'city_ru',
    DROP 'city_ua',
    DROP 'city_be',
    DROP 'city_en',
    DROP 'city_es',
    DROP 'city_pt',
    DROP 'city_de',
    DROP 'city_fr',
    DROP 'city_it',
    DROP 'city_pl',
    DROP 'city_ja',
    DROP 'city_lt',
    DROP 'city_lv',
    DROP 'city_cz',
    DROP 'area_ru',
    DROP 'area_ua',
    DROP 'area_be',
    DROP 'area_en',
    DROP 'area_es',
    DROP 'area_pt',
    DROP 'area_de',
    DROP 'area_fr',
    DROP 'area_it',
    DROP 'area_pl',
    DROP 'area_ja',
    DROP 'area_lt',
    DROP 'area_lv',
    DROP 'area_cz';