-- MySQL Script generated by MySQL Workbench
-- Tue Feb 12 14:57:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema geek_db_week_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema geek_db_week_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `geek_db_week_1` DEFAULT CHARACTER SET utf8 ;
USE `geek_db_week_1` ;

-- -----------------------------------------------------
-- Table `geek_db_week_1`.`страна`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geek_db_week_1`.`страна` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `страна` VARCHAR(70) NOT NULL,
  `столица` VARCHAR(70) NOT NULL,
  `территория` FLOAT NULL,
  `население` FLOAT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `country_name_UNIQUE` (`страна` ASC) VISIBLE,
  UNIQUE INDEX `столица_UNIQUE` (`столица` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geek_db_week_1`.`область`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geek_db_week_1`.`область` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `область` VARCHAR(150) CHARACTER SET 'utf8' NOT NULL,
  `административный_центр` VARCHAR(150) CHARACTER SET 'utf8' NOT NULL,
  `площадь` FLOAT NULL,
  `часовой_пояс` VARCHAR(3) NOT NULL DEFAULT 'МСК',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `наименование_области_UNIQUE` (`область` ASC) VISIBLE,
  UNIQUE INDEX `административный_центр_UNIQUE` (`административный_центр` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geek_db_week_1`.`район`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geek_db_week_1`.`район` (
  `id` INT GENERATED ALWAYS AS () VIRTUAL,
  `район_(если_есть)` VARCHAR(150) CHARACTER SET 'utf8' NULL,
  `административные_единицы` VARCHAR(150) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`id`, `район_(если_есть)`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geek_db_week_1`.`город`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geek_db_week_1`.`город` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `наименование` VARCHAR(150) NOT NULL,
  `город` TINYINT(1) NULL,
  `поселок` TINYINT(1) NULL,
  `деревня` TINYINT(1) NULL,
  `население` FLOAT NULL,
  `площадь` FLOAT NULL,
  `мэр` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`, `мэр`),
  UNIQUE INDEX `наименование_UNIQUE` (`наименование` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
